vim.keymap.set("i", "jj", "<Esc>", { silent = true })
vim.keymap.set("n", "[b", ":bprevious<cr>", { remap = false, silent = true })
vim.keymap.set("n", "]b", ":bprevious<cr>", { remap = false, silent = true })
vim.keymap.set("n", "<C-h>", "<C-w>h", { remap = false })
vim.keymap.set("n", "<C-l>", "<C-w>l", { remap = false })
vim.keymap.set("n", "<C-j>", "<C-w>j", { remap = false })
vim.keymap.set("n", "<C-k>", "<C-w>k", { remap = false })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
